<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit90a58144d6558a80884af2a2d88da2ff
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TripSorter\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TripSorter\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit90a58144d6558a80884af2a2d88da2ff::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit90a58144d6558a80884af2a2d88da2ff::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
